#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");

# Lab 2. TODO Part 2: add an entry("trace") line.
#
# Each entry() call emits four lines of assembly into user/usys.S:
#
#     .global sysinfo
#     sysinfo:
#      li a7, SYS_sysinfo      # the syscall number, from kernel/syscall.h
#      ecall                   # trap into the kernel
#      ret
#
# The arguments are already in a0..a5 when the stub is entered, and the
# kernel's return value is already in a0 when it comes back, so the stub
# needs no argument shuffling at all -- the RISC-V C calling convention and
# the xv6 syscall convention were chosen to agree.
#
# Miss the entry out and the C compiler is perfectly happy (it saw the
# prototype in user/user.h) and the LINK fails with "undefined reference".
entry("sysinfo");
entry("settickets");
entry("getpinfo");
